min_amount: 500
    max_amount: 100000
    max_income_ratio: 0.8
    
  # ⭐ Credit Score Rules
  credit_score_rules:
    excellent: 750
    good: 700
    fair: 650
    poor: 600
    very_poor: 300
    
  # 🏠 Home Ownership Impact
  home_ownership_weights:
    OWN: 1.2
    MORTGAGE: 1.1
    RENT: 1.0
    OTHER: 0.9
    
  # 🎓 Education Impact
  education_weights:
    Doctorate: 1.3
    Master: 1.2
    Bachelor: 1.1
    Associate: 1.05
    "High School": 1.0
    
  # 💼 Loan Purpose Risk
  loan_intent_risk:
    EDUCATION: 0.2
    HOMEIMPROVEMENT: 0.3
    DEBTCONSOLIDATION: 0.5
    MEDICAL: 0.4
    PERSONAL: 0.6
    VENTURE: 0.8
    
  # ⚠️ Risk Thresholds
  risk_thresholds:
    very_low: 0.2
    low: 0.4
    medium: 0.6
    high: 0.8
    very_high: 1.0
    
  # 📊 Auto-Decision Rules
  auto_decision:
    auto_approve_threshold: 0.85
    auto_reject_threshold: 0.15
    manual_review_min: 0.15
    manual_review_max: 0.85